# PyTorch AutoGrad 기능

In [118]:
import torch

In [119]:
x = torch.FloatTensor([[1, 2],  # (모델 파라미터로 예측한) 예측값
                       [3, 4]]).requires_grad_(True) # 미분에 참여할 것인가? True (Loss를 미분할 예정)
x  # 나중에 x로 미분할 예정

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [120]:
# element-wise 연산
x1 = x + 2
x2 = x - 2
x3 = x1 * x2

In [121]:
print(x1)
print(x2)
print(x3)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [122]:
# y(훗날 loss) ->  y는 x에 대해 미분 가능하다.
y = x3.sum()   # y는 scalar
y

tensor(14., grad_fn=<SumBackward0>)

In [123]:
# y를 x에 대해 미분하기 전 x 요소들의 기울기를 살펴보면,
print(x.grad)

None


In [124]:
# y 미분 실행   -> 결과: x.grad, 2x2의 기울기가 생긴다.
y.backward()

In [125]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


$$\begin{gathered}
x=\begin{bmatrix}
x_{(1,1)} & x_{(1,2)} \\
x_{(2,1)} & x_{(2,2)}
\end{bmatrix}\\
\\
x_1=x+2 \\
x_2=x-2 \\
\\
\begin{aligned}
x_3&=x_1\times{x_2} \\
&=(x+2)(x-2) \\
&=x^2-4
\end{aligned} \\
\\
\begin{aligned}
y&=\text{sum}(x_3) \\
&=x_{3,(1,1)}+x_{3,(1,2)}+x_{3,(2,1)}+x_{3,(2,2)}
\end{aligned} \\
\\
\text{x.grad}=\begin{bmatrix}
\frac{\partial{y}}{\partial{x_{(1,1)}}} & \frac{\partial{y}}{\partial{x_{(1,2)}}} \\
\frac{\partial{y}}{\partial{x_{(2,1)}}} & \frac{\partial{y}}{\partial{x_{(2,2)}}}
\end{bmatrix} \\
\\
\frac{∂y}{∂x}=2x
\end{gathered}$$

In [77]:
# y를 x에 대해 미분한 x의 기울기(∂y/∂x = 2x)를 살펴보면,
print(x.grad)  # 2x2 matrix 기울기가 생겼다.

tensor([[2., 4.],
        [6., 8.]])


In [126]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [107]:
# x3도 gradient를 가지고 있는 텐서 이므로 numpy 변환이 안된다. 먼저 detach 변환이 필요하다.
x3.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [108]:
x3

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)

In [109]:
# detach : 미분 함수 타입에서 숫자 타입으로 변환해준다. 
# autograd가 연산할 때마다 computational graph를 그리는데 이것을 끊어주는 것. 
# 그래야 넘파이와의 산술연산이 가능해진다.
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)